spring:
  datasource:
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 3
        max-concurrency: 6
rabbit:
  celebrity-queue:
    batchSize: 50
    batchTimeOut: 10000
grpc:
  client:
    dialog-service:
      negotiation-type: plaintext