spring:
  datasource:
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  cache:
    caffeine:
      spec: maximumSize=1,refreshAfterWrite=30s