spring:
  datasource:
    master:
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    slave1:
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
    slave2:
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  cache:
    caffeine:
      spec: maximumSize=1,refreshAfterWrite=30s