spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/mydb
    slave1:
      url: jdbc:postgresql://localhost:5433/mydb
    slave2:
      url: jdbc:postgresql://localhost:5434/mydb
logging:
  level:
    ru:
      otus:
        highload:
          sn: DEBUG
