spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase-changelog.xml
